version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oddbits
      - MONGO_INITDB_ROOT_PASSWORD=yellowcamelridesbike
  api:
    build:
      context: ./api-build
      dockerfile: Dockerfile
    ports:
      - "9090:9000"
    links:
      - db
    environment:
      - MONGO_CONNECTION=db:27017
      - MONGO_USERNAME=oddbits
      - MONGO_PASSWORD=yellowcamelridesbike
